#PBS -N trap_c
#PBS -q route
#PBS -l nodes=1:ppn=8
#PBS -l walltime=1:00:00        
##PBS -m bea
# -- change below to your email address for notification
#PBS -M discard@puma.kean.edu
module load gcc720
PROGRAM='./traprule'
cd $PBS_O_WORKDIR
# run the program
N_NODES=`cat $PBS_NODEFILE | wc -l`
time ./traprule 1000
time ./traprule 1000000
time ./traprule 1000000000
time ./traprule 10000000000
exit 0
